export class DataHelper {
    node = {
        label: '',
        ParentID: null,
        ID: null,
        Type: null,
        SubType: null,
        EU: '',
        Min: null,
        Max: null,
        Mul: null,
        Exp: false,
        Program: '',
        TagName: '',
        UID: null,
        iStartD: null,
        bHasTrigger: false,
        updateRate: null,
        isMulp: false,
        InternalIndex: null,
        children: [],
        oTreeNode: '',
        rung: null,
        routine: '',
        sProgramParent: '',
        sParentTagName: '',
        updateRadio: '',
        isAoi: false,
        nameAoi: null,
        lInfoAtt: [],
        isInjected: false
    }
    nodeValueType = {
        label: '',
        ParentID: null,
        ID: null,
        Type: null,
        SubType: null,
        EU: '',
        Min: null,
        Max: null,
        Mul: null,
        Exp: false,
        Program: '',
        TagName: '',
        UID: null,
        iStartD: null,
        bHasTrigger: false,
        updateRate: null,
        isMulp: false,
        InternalIndex: null,
        children: [],
        oTreeNode: '',
        rung: null,
        routine: '',
        sProgramParent: '',
        sParentTagName: '',
        updateRadio: '',
        valueType: '',
        isAoi: false,
        nameAoi: null,
        lInfoAtt: [],
        isInjected: false
    }

    Tree = { "nameInModel": "Root", "ParentID": 0, "ID": 1, "Type": 0, "SubType": 0, "EU": "", "Min": 0.0, "Max": 0.0, "Mul": 0.0, "Exp": true, "Program": "MainProgram", "TagName": "TestLogic", "UID": 0, "iStartD": 112, "bHasTrigger": false, "updateRate": 0.3072, "isMulp": false, "InternalIndex": 19, "lChildrens": []}
}
